#!/bin/bash

VERSION="0.1"

# @getoptions
parser_definition() {
  setup   REST help:usage \
    -- "Usage: example.sh [options]... [arguments]..." ''
  msg -- 'Options:'
  flag    FLAG    -f --flag \
    -- "takes no arguments"
  param   PARAM   -p --param \
    -- "takes one argument"
  option  OPTION  -o --option on:"default" \
    -- "takes one optional argument"
  disp    :usage  -h --help
  disp    VERSION    --version
}
# @end

# @gengetoptions parser -i parser_definition parse
# @end
eval "$(getoptions parser_definition) exit 1"

echo "FLAG: $FLAG, PARAM: $PARAM, OPTION: $OPTION"
if [ "$#" -eq 0 ]; then
  :
  #usage >&2
  #exit 1
else
  printf '%s\n' "$@" # rest arguments
fi
