#!/bin/bash
set -eu -o pipefail

# @getoptions
VERSION="0.1"
ACTIONS="get store erase"

version() {
  printf "%s\n" "${0##*/} $VERSION"
}
parser_definition() {
  setup   ARGS help:usage \
    -- "Usage: ${0##*/} [OPTIONS] ACTION" ''
  msg -- 'Actions:'
  msg -- "  $ACTIONS"
  cmd     get
  cmd     store
  cmd     erase
  msg -- ""
  msg -- 'Options:'
  flag    TRY_FIFO    --try-fifo \
    -- "takes no arguments"
  param   PPP      -p --ppp \
    -- "takes one argument"
  option  OOO      -o --ooo on:"default" \
    -- "takes one optional argument"
  param   FILE        --file \
    -- "use FILE to lookup and store encrypted credentials"
  param   GPG         --gpg \
    -- "GPG program instead of \"gpg\""
  param   RECP     -r --recipeint \
    -- "recipient"
  flag    VERBOSE  -v --verbose counter:true
  disp    :usage   -h --help
  disp    :version    --version
}
# @end

# @gengetoptions parser -i parser_definition parse
# @end
eval "$(getoptions parser_definition) exit 1"

info() {
  if [[ "$VERBOSE" -gt 0 ]]; then
    printf >&2 '%s\n' "$@"
  fi
}

infof() {
  if [[ "$VERBOSE" -gt 0 ]]; then
    printf >&2 "$@"
  fi
}

try_fifo() {
  info "VERBOSE: ${VERBOSE-}"
  local tmpdir="${CREDENTIAL_GPG_TMPDIR-"${TMPDIR-/tmp}"}"

  fifo="$(mktemp --dry-run --tmpdir="$tmpdir" tmp.XXXXXXXXXX.fifo)"
  trap cleanup EXIT
  mkfifo -- "$fifo"

  read -p "nan de mo doo zo: " REPLY

  cat >&2 -- "$fifo" &
  #cat >&2 <"$fifo" &
  sleep 0.1
  {
    printf "%s\n" "(pop first) PWD: $PWD"
    printf "%s\n" "(pop fitst) REPLY: $REPLY"
  } >"$fifo"

  {
    printf "%s\n" "(put first) PWD: $PWD"
    printf "%s\n" "(put fitst) REPLY: $REPLY"
  } >"$fifo"
  sleep 0.1
  cat >&2 -- "$fifo"

  return 0
}

cleanup() {
  if [[ -n "$VERBOSE" ]]; then
    rm -vf -- "$fifo"
  else
    rm -f -- "$fifo"
  fi
}

get() {
  decrypt

  git credential-store --file "$tmp" get

  #rm

  return 0
}

decrypt() {
  #cd "$tmpdir" || exit 1

  if [[ -n "$RECP" ]]; then
    "$GPG" -r "$RECP" -o "$tmp" --decrypt "$enc"
  else
    "$GPG" -o "$tmp" --decrypt "$enc"
  fi
}

store() {
  decrypt

  git credential-store --file "$tmp" store

  encrypt

  #rm

  return 0
}

erase() {
  info "Not implemented yet"

  return 1
}

encrypt() {
  info "Not implemented yet"

  return 1

  if [[ -n "$RECP" ]]; then
    "$GPG" -r "$RECP" -o "$enc" --encrypt "$tmp"
  else
    "$GPG" -o "$enc" --encrypt "$tmp"
  fi
}

#info "TRY_FIFO: $TRY_FIFO, PPP: $PPP, OOO: $OOO"
if [ "$#" -eq 0 ]; then
  if [[ -n "$TRY_FIFO" ]]; then
    try_fifo
  else
    usage >&2
    exit 1
  fi
else
  cmd="$1"; shift
  case "$cmd" in
  get|store|erase)
    GPG="${GPG:-gpg}"
    tmpdir="${CREDENTIAL_GPG_TMPDIR-"${TMPDIR-/tmp}"}"
    tmp="$tmpdir/git-credentials"
    if [[ -n "$FILE" ]]; then
      enc="$FILE"
    else
      enc="$HOME/.git-credentials.gpg"
      if [[ ! -e "$enc" && -e "${XDG_CONFIG_HOME:-.config}/git/credentials.gpg" ]]; then
        enc="${XDG_CONFIG_HOME:-.config}/git/credentials.gpg"
      fi
    fi

    "$cmd"
    ;;
  *)
    info "cmd: $cmd"
    printf "%s\n" "Actions is one of ${ACTIONS// /,}" >&2
    exit 1
    ;;
  esac
fi
